In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Cálculo de autovectores: Método de la potencia

## Ejercicio 1: Metodo de la potencia

Implementar el método de la potencia considerando algún criterio de parada (además del corte por cantidad de iteraciones)

In [21]:
def power_iteration(A, niter=10_000, eps=1e-6):
    """
    Calcula el autovector al autovalor asociado de valor máximo

    Devuelve (a, v) con a autovalor, y v autovector de A

    Arguments:
    ----------

    A: np.array
        Matriz de la cual quiero calcular el autovector y autovalor

    niter: int (> 0)
        Cantidad de iteraciones

    eps: Epsilon
        Tolerancia utilizada en el criterio de parada
    """
    a = []
    v = np.random.uniform(1, -1, A.shape[0])
    v = v /np.linalg.norm(v,2)
    l0 = v.T @ A @ v / v.T @ v
    v1 = A @ v
    v1 = v1 / np.linalg.norm(v1, 2)
    l1 = (v1.T @ A @ v1) / (v1.T @ v1)
    a.append(l1)
    iter = 0
    while np.abs(l1 - l0) / np.abs(l0) > eps and iter < niter: 
        l0 = l1
        vec = v1
        v1 = A @ v1
        v1 = v1 / np.linalg.norm(v1, 2)
        l1 = (v1.T @ A @ v1) / (v1.T @ v1)
        a.append(l1)
        iter += 1
    
    v = v1
    return a, v

Verifiquemos la implementación con ejemplos con autovalores y autovectores conocidos.

a) Matriz D diagonal con autovalores y autovectores conocidos

$$
D = \begin{pmatrix}
d_1    &0     &0      &0      &\\
0      &d_2   &0      &0      &\\
\vdots &\vdots&\ddots &\vdots &\\
0      &0     &0      &d_n    & \\
\end{pmatrix}
$$


b) Matriz A semejante a una matriz diagonal D con autovalores conocidos.

$$
A = Q \begin{pmatrix}
d_1    &0     &0      &0      &\\
0      &d_2   &0      &0      &\\
\vdots &\vdots&\ddots &\vdots &\\
0      &0     &0      &d_n    & \\
\end{pmatrix} Q^T
$$

con $Q = I - 2 v v^T$, $||v||_2=1$ la matriz de reflexión de Householder que sabemos que es ortogonal


In [42]:
D = np.diag([5.0, 4.0, 3.0, 2.0, 1])
rows, cols = D.shape
# Vector v aleatorio y de norma 1
v = np.random.uniform(1, -1, rows)
v = v / np.linalg.norm(v,2)
print(np.linalg.norm(v,2))
# Matriz de Householder
B = np.eye(rows, cols) - np.multiply(v @ v.T, 2)
print(B)
# Matriz a diagonalizar, recordar B es simétrica y ortogonal
M = B @ D @ B.T
print(M)
print(np.linalg.eig(M))

l, v = power_iteration(M,niter=100, eps=1e-16)
l, v

1.0
[[-1. -2. -2. -2. -2.]
 [-2. -1. -2. -2. -2.]
 [-2. -2. -1. -2. -2.]
 [-2. -2. -2. -1. -2.]
 [-2. -2. -2. -2. -1.]]
[[45. 42. 44. 46. 48.]
 [42. 48. 46. 48. 50.]
 [44. 46. 51. 50. 52.]
 [46. 48. 50. 54. 54.]
 [48. 50. 52. 54. 57.]]
EigResult(eigenvalues=array([243.67312839,   4.52690695,   1.14852885,   2.266642  ,
         3.3847938 ]), eigenvectors=array([[ 0.41304901, -0.81078757,  0.18819874, -0.2153492 , -0.30036643],
       [ 0.42995889,  0.56609947,  0.20202788, -0.26806744, -0.61805446],
       [ 0.44672826,  0.13948822,  0.23079559, -0.46455787,  0.71546928],
       [ 0.46335885,  0.05053186,  0.32713504,  0.81276619,  0.12304024],
       [ 0.47985238,  0.01201991, -0.87377459,  0.07322352,  0.02744999]]))


([np.float64(225.6602544661792),
  np.float64(243.66819608873752),
  np.float64(243.67312698170898),
  np.float64(243.67312839056154),
  np.float64(243.67312839099566),
  np.float64(243.67312839099577),
  np.float64(243.6731283909958),
  np.float64(243.6731283909958)],
 array([0.41304901, 0.42995889, 0.44672826, 0.46335885, 0.47985238]))

In [44]:
# Verificar l es autovalor dominante
print(np.allclose(M@v, l[-1] * v))

# Verificar v es autovector
assert(v in np.linalg.eig(M)[1])

True


AssertionError: 

Otra forma de chequear:

Si llamamos  $\hat v_1$ al autovector dominante estimado y $\hat \lambda_1$ al autovalor asociado estimado, entonces chequeemos que cumple con ser un autovector por definición:

$$ A \hat v_1 \approx \hat \lambda_1 v_1$$

y por lo tanto

$$ || A \hat v_1 - \hat \lambda_1 v_1 || < \epsilon $$

para  $\epsilon$  suficientemente chico (que dependera de la aplicación y el contexto).
Para este caso, probar con $10^{-6}$



In [43]:
error = np.linalg.norm(M@v-l[-1]*v,2)
if error < 10e-6:
    print(True)

True


## Ejercicio 2: Velocidad de convergencia

Mostrar la convergencia de la sucesión de autovalores $\{\lambda_{k}\}_{k \in \mathbb{N}}$ al autovalor dominante.

Utilizar la matriz M como se definió en el ejercicio anterior con autovalores $[5,4,3,2,1]$

In [ ]:
plt.plot(...)
plt.xlabel("k (iteraciones)")
plt.ylabel("$\lambda_k$")

Repetir el análisis anterior pero para una matriz M con autovalores $[5, 4.9, 3,2,1]$. ¿De qué parece depender la velocidad de convergencia?

In [ ]:
# COMPLETAR

---


Definición: Sea ${\alpha_n}$ una sucesión que converge a $\alpha$. Sea ${\beta_n}$ convergente a 0.

Decimos que ${\alpha_n}$ tiene orden de convergencia $O(\beta_n)$ (es decir, que $\alpha_n$ converge tan rápido como $\beta_{n}$) si existe c > 0 tal que:

$$|\alpha_n − \alpha| ≤ c\beta_n$$ para todo
n suficientemente grande.



Analizar la velocidad de convergencia para la sucesión {$\lambda_k\}_{k}$ del autovalor dominante $\lambda_1 = 5$.

Verificar que, en caso de tomar cociente de Rayleigh, se obtiene convergencia cuadrática:

$$ \{\lambda_k\}_{k} \in O((\frac{\lambda_2}{\lambda_1})^{2k})$$



In [ ]:
# COMPLETAR

 ## Ejercicio 3: Metodo de la potencia inverso

Obtener el autovalor más chico de M (junto a su autovector) utilizando el método de la potencia inverso.

In [ ]:
# COMPLETAR

## Ejercicio 4: Metodo de la potencia + Deflación

Implementar método de la potencia + deflación

In [ ]:
def eigen(A, num=2, niter=10000, eps=1e-6):
    """
    Calculamos num autovalores y autovectores usando método de la potencia+deflación
    """
    A = A.copy()
    eigenvalues = []
    eigenvectors = np.zeros((A.shape[0], num))
    for i in range(num):
        
        pass
    return np.array(eigenvalues), eigenvectors

Calcular todos los autovalores y autovectores de la matriz M definida inicialmente.

Verificar que los errores de las aproximaciones obtenidas

$$ || A \hat v_i - \hat \lambda_i v_i || < \epsilon $$

se encuentren dentro de una tolerancia de $10^{-6}$.

Verificar que con los autovectores obtenidos, se obtiene una diagonalización de la matriz A.

In [ ]:
D = np.diag([5.0, 4.0, 3.0, 2.0, 0])


M = ...

l, V = eigen(M, 5, niter=...,eps=..)

# Verificar error dentro de tolerancia

# Verificar que diagonalizacion de A


## Ejercicio 5: Más Casos de prueba para divertirse un rato

Corroborar que para la siguiente matriz se cumplen todas las hipótesis del método de la potencia + deflación.

Verificar con la noción de error del ejercicio anterior, que pueden encontrarse todos sus autovectores y autovalores.

In [ ]:
A = np.array([
  [ 7,  2,  -3],
  [ 2,  2,  -2],
  [-3, -2,  -2]
])


Para una matriz A cualquiera (considerar por ejemplo la anterior), estudiar la relación entre los autovectores y autovalores de $AA^T$ y $A^TA$.

Obtenerlos mediante el método de la potencia + deflación y verificar que se cumpla dicha relación.

In [ ]:
TA = A.T @ A
AT = A @ A.T
wta, VTA, _ = eigen(AT, num=3, niter=20000, eps=1e-24)
wat, VAT, _ = eigen(TA, num=3, niter=20000, eps=1e-24)


# Verificar relacion entre autovalores y autovectores
assert(...)
assert(...)

Analizar lo que ocurre en este caso

In [ ]:
A = np.array([
  [7, 2, 3],
  [0, 2, 0],
  [-6, -2, -2]
])

w, V, _  = eigen(A, num=3, niter=20_000, eps=1e-14)
print("w")
print(w)
print("V")
print(V)

print("-"*20)
for i in range(len(A)):
    print(i)
    print(np.allclose(A @ V[:, i], w[i] * V[:,i]))

print("-"*20)

print("Usando numpy")
w2, V2 = LA.eigh(A)
print(w2)


for i in range(len(A)):
    print(i)
    print(np.allclose(A @ V2[:, i], w2[i] * V2[:,i]))



<div>
<img src="https://cdn131.picsart.com/331981814059211.png?to=crop&type=webp&r=1008x1096&q=85"  width="200">
</div>


## Otros casos más divertidos

¿Qué pasa si tenemos r autovalores iguales?

In [ ]:
D = np.diag(np.arange(10))
D[1,1] = 10
D[2,2] = 10
print(D)

# Matriz de Householder
B = ...

# Matriz a diagonalizar
M = ...

# Chequear utilizando la noción de error del ejercicio 4 para todo autovector y autovalor



Opcionales:

Asumiendo que el autovalor dominante tiene multiplicidad r, probar que el método converge a una combinación lineal del autoespacio dominante.

---
